import Image from "next/image";
import "../globals.css";
import "./layout.css";
import { Inter } from "next/font/google";
import { auth1, auth2, auth3 } from "@/assets";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Curahunt-auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body className={inter.className}>
        <div className="bg-auth">
          <Image src={auth1} alt=" auth 1" width={500} height={500} />
          <Image src={auth2} alt=" auth 2" width={500} height={500} />
          <Image src={auth3} alt=" auth 3" width={500} height={500} />
          <Image src={auth1} alt=" auth 1" width={500} height={500} />
        </div>
        <div className="auth-container">
          <span>WELCOME BACK!</span>
          <main>{children}</main>
          <span>Privacy Policy | Terms & Conditions</span>
        </div>
      </body>
    </html>
  );
}
