import "./notice.css";

const Notice = () => {
  return (
    <div className="notice">
      <h1>MEDICAL NEWS</h1>
      <div>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
        <span>
          New AI tool can accurately diagnose eye conditions, could help detect…
          ...
        </span>
      </div>
    </div>
  );
};

export default Notice;
